/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Mmilagani' at '11/1/18 12:57 PM' with Gradle 2.14.1
 *
 * @author Mmilagani, @date 11/1/18 12:57 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
